### ISSUE TITLE
What should i do?

### ISSUE THREAD

**Issue by dogex21** [roogue/osu-collector-dl#19]
I am getting the 418 error how should i fix that?

**Comment by roogue** [comment]
Hi, apparently this is an IP-Ban from the beatmapset download service provider due to too many download requests. Sorry I couldn't help much at this moment, try to avoid using the download function for now, and wait for the next update. (you can use [Collection Manager](https://github.com/Piotrekol/CollectionManager) for temporary replacement of download function)

more information: https://github.com/roogue/osu-collector-dl/issues/18

**Comment by dogex21** [comment]
ok thank you!

2024-07-10, tr, 12:59 weiisennnz ***@***.***> rašė:

**Comment by roogue** [comment]
Fixed in [v2.7.5](https://github.com/roogue/osu-collector-dl/releases/tag/v2.7.5)
